### ISSUE TITLE
Different text coding for language file on githuib and application

### ISSUE THREAD

**Issue by bovirus** [dvdforge/ccode_translations#1]
@dvdforge 

Could you please explain me the scope of different text coding of language files in the app and on github. Ex:

Ccode_ENU.ini - app - coded as UTF-16 LE BOM - Size 15.602 bytes
Ccode_ENU.ini - Github - coded as UTF-8 BOM - Size 7.803 bytes

I believe that the file in the app should have teh same coding of files in the app.

Thanks.

**Comment by imgdrive** [comment]
UTF-8 with BOM is used in GitHub, because GitHub cannot handle UTF-16 correctly.

When release, I used a script to automatic convert UTF-8 to UTF-16. Although CCode can use UTF-8 .ini file, but that need to do extra convert step. BTW: Windows .ini functions cannot handle UTF-8 file (only support ANSI or UTF-16 LE BOM).

For files submit to GitHub, please always use UTF-8 BOM.

**Comment by bovirus** [comment]
@dvdforge 

I believe that it's impprtant to add this info about coding regarding language text file in home of this section.

Thanks. KR
